Repository Think-Tank-6/Voice-Of-the-Star, pull requests merged in 2023-12, with the labels that each got.

#2 [build#1] Initial commit
  .gitignore
  app/__pycache__/main.cpython-310.pyc
  app/api/__pycache__/star.cpython-310.pyc
  app/api/star.py
  app/database/__pycache__/connection.cpython-310.pyc
  app/database/__pycache__/orm.cpython-310.pyc
  app/database/__pycache__/repository.cpython-310.pyc
  app/database/connection.py
  app/database/orm.py
  app/database/repository.py
  app/main.py
  app/schema/__pycache__/request.cpython-310.pyc
  app/schema/__pycache__/response.cpython-310.pyc
  app/schema/request.py
  app/schema/response.py
  requirements.txt
Labels: build

#8 [fix #7] requirements.txt 수정
  app/requirements.txt
  requirements.txt
Labels: fix, emergency

#10 [feat #9] 로그인 API, jwt 생성 service 구현
  app/__pycache__/main.cpython-310.pyc
  app/api/__pycache__/auth.cpython-310.pyc
  app/api/__pycache__/star.cpython-310.pyc
  app/api/auth.py
  app/database/__pycache__/connection.cpython-310.pyc
  app/database/__pycache__/orm.cpython-310.pyc
  app/database/__pycache__/repository.cpython-310.pyc
  app/database/repository.py
  app/schema/__pycache__/request.cpython-310.pyc
  app/schema/__pycache__/response.cpython-310.pyc
  app/schema/request.py
  app/schema/response.py
  app/service/__pycache__/auth.cpython-310.pyc
  app/service/auth.py
Labels: feat

#13 [docs #11] requirements.txt 업데이트
  requirements.txt
Labels: doc
