Repository Think-Tank-6/Voice-Of-the-Star, pull requests merged in 2024-01, with the labels that each got.

#17 [feat #16] star 생성, 조회, 수정, 삭제 API 유저 검증 적용
  app/__pycache__/main.cpython-310.pyc
  app/api/__pycache__/auth.cpython-310.pyc
  app/api/__pycache__/star.cpython-310.pyc
  app/api/star.py
  app/database/__pycache__/connection.cpython-310.pyc
  app/database/__pycache__/orm.cpython-310.pyc
  app/database/__pycache__/repository.cpython-310.pyc
  app/database/orm.py
  app/database/repository.py
  app/service/__pycache__/auth.cpython-310.pyc
  app/service/auth.py
Labels: feat

#20 [build #12] ai-models initial setting
  ai-models/requirements.txt
  ai-models/speaker-identification/README.md
  ai-models/text-generation/README.md
  ai-models/voice-cloning/README.md
Labels: build

#25 [fix #22] router 명칭 변경
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/database/repository.py
  backend/app/main.py
  backend/app/service/auth.py
Labels: fix

#28 [feat #26] speaker identification 추가
  .gitignore
  ai-models/speaker-identification/clova_speech.py
  ai-models/speaker-identification/postprocessing.py
  ai-models/speaker-identification/test.py
Labels: feat

#32 [feat #30] 특징 추출 프롬프트 구현
  ai-models/text-generation/extract_characteristics.py
  ai-models/text-generation/prompt_data/extract_characteristic.txt
  ai-models/text-generation/run_prompt.py
Labels: feat

#33 [fix #31] user, star 데이터베이스 관련 재정의
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/schema/request.py
  backend/app/schema/response.py
  docker-compose.yml
Labels: fix

#39 [fix #37] user 테이블 변경에 따른 관련 코드 수정
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/schema/request.py
  backend/app/schema/response.py
Labels: fix

#41 [feat #24] 채팅 기능 추가
  README.md
  backend/app/api/chat.py
  backend/app/main.py
  backend/requirements.txt
Labels: feat

#40 [feat #34] 채팅 프롬프트 구현
  ai-models/text-generation/characteristic_generation.py
  ai-models/text-generation/chat_generation.py
  ai-models/text-generation/prompt_data/system_input.txt
  ai-models/text-generation/run_prompt.py
Labels: feat

#43 [feat/42] MongoDB 연결
  backend/README.md
  backend/app/api/chat.py
  backend/app/database/connection.py
  backend/app/database/mpngo.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  docker-compose.yml
Labels: feat

#44 [feat #35] 카카오 API 백엔드 연동
  backend/app/api/user.py
Labels: feat, emergency

#48 [fix #46] 파일 오생성 삭제
  backend/app/database/mpngo.py
Labels: fix, emergency

#50 [fix #49] docker-compose 긴급수정
  docker-compose.yml
Labels: fix, emergency

#52 [doc #51] requirements.txt 수정
  backend/requirements.txt
Labels: doc, emergency

#47 [doc #45] ai-models requirements.txt 작성
  ai-models/requirements.txt
Labels: doc

#54 [feat #53] 카카오 간편로그인 생일부분 DB입력 추가
  backend/app/api/user.py
Labels: feat

#56 [fix #55] ai 디렉토리 이름 변경
  ai_models/__init__.py
  ai_models/speaker_identification/__init__.py
  ai_models/text_generation/__init__.py
  ai_models/voice_cloning/__init__.py
Labels: fix

#65 [fix #61] star 업로드 방식 및 DB구조 변경 관련 코드 수정
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/main.py
  backend/app/schema/request.py
  backend/app/schema/response.py
  backend/app/service/ai_serving.py
  backend/requirements.txt
Labels: fix

#68 [doc #67] requirements.txt 업데이트
  backend/requirements.txt
Labels: doc

#74 [feat #72] 이메일 중복 체크 API 구현
  .gitignore
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/schema/request.py
  backend/app/service/ai_serving.py
Labels: feat

#75 [fix #73] import 에러 해결
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: fix

#81 [feat #80] mypage 조회 수정 API 구현 및 ai_modles 폴더 이동
  backend/app/ai_models/README.md
  backend/app/ai_models/__init__.py
  backend/app/ai_models/requirements.txt
  backend/app/ai_models/speaker_identification/README.md
  backend/app/ai_models/speaker_identification/__init__.py
  backend/app/ai_models/speaker_identification/clova_speech.py
  backend/app/ai_models/speaker_identification/postprocessing.py
  backend/app/ai_models/speaker_identification/test.py
  backend/app/ai_models/text_generation/README.md
  backend/app/ai_models/text_generation/__init__.py
  backend/app/ai_models/text_generation/characteristic_generation.py
  backend/app/ai_models/text_generation/chat_generation.py
  backend/app/ai_models/text_generation/preprocessing.py
  backend/app/ai_models/text_generation/prompt_data/extract_characteristic.txt
  backend/app/ai_models/text_generation/prompt_data/system_input.txt
  backend/app/ai_models/text_generation/run_prompt.py
  backend/app/ai_models/text_generation/test.py
  backend/app/ai_models/text_generation/token_counter.py
  backend/app/ai_models/text_generation/token_limit.py
  backend/app/ai_models/text_generation/token_test.py
  backend/app/ai_models/voice_cloning/README.md
  backend/app/ai_models/voice_cloning/__init__.py
  backend/app/ai_models/voice_cloning/test.py
  backend/app/ai_models/voice_cloning/xtts.py
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  backend/app/main.py
  backend/app/schema/request.py
  backend/app/schema/response.py
  backend/app/service/ai_serving.py
Labels: feat

#84 [doc #82] requirements.txt 업데이트
  backend/app/ai_models/requirements.txt
  backend/requirements.txt
Labels: doc

#85 [Feat #83] Speaker Identification 기본 구현
  backend/app/ai_models/speaker_identification/clova_speech.py
  backend/app/ai_models/speaker_identification/postprocessing.py
  backend/app/ai_models/speaker_identification/test.py
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: feat

#79 [feat #66] 프롬프트 서빙 구현
  backend/app/ai_models/text_generation/token_counter.py
  backend/app/ai_models/text_generation/token_limit.py
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
  backend/requirements.txt
Labels: feat

#93 [fix #92] ai_serving 오류 수정
  backend/app/service/ai_serving.py
Labels: fix, emergency

#90 [feat #88] 유저 패스워드 변경 API 구현
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/schema/request.py
Labels: feat

#94 [feat #91] 채팅 백엔드 GPT 모듈화 연결
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/database/connection.py
  backend/app/database/orm.py
  backend/app/database/repository.py
Labels: feat

#97 [feat #96] star voice selection, combining 구현
  backend/app/ai_models/speaker_identification/postprocessing.py
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: feat

#99 [feat #98] star 채팅 답변 생성 로직 연결
  backend/app/api/chat.py
Labels: feat

#102 [refactor #101] room table 삭제
  backend/app/api/chat.py
  backend/app/database/orm.py
  backend/app/database/repository.py
Labels: refactor

#106 [fix #103] star prompt 수정
  backend/app/ai_models/text_generation/token_limit.py
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: fix

#113 [feat #108] 관리자 회원가입 및 로그인, 리스트 불러오기
  backend/app/api/admin.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  backend/app/main.py
  backend/app/schema/request.py
  backend/app/schema/response.py
  backend/app/service/auth.py
Labels: feat

#112 [feat #111] 보이스피싱 탐지 채팅 연결 구현
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
Labels: feat

#117 [feat #110] 웹소켓 연결 완료
  backend/app/api/chat.py
  backend/app/database/connection.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  backend/app/security.py
Labels: feat

#116 [feat #95] 보이스피싱 탐지기법 구현
  backend/app/ai_models/text_generation/crime_prevention.py
  backend/app/ai_models/text_generation/prompt_data/crime_prevention.txt
Labels: feat

#120 [fix #119] security 코드 수정
  backend/app/security.py
Labels: fix

#122 [feat #118] 채팅 연결 구현
  backend/app/ai_models/text_generation/chat_generation.py
  backend/app/api/chat.py
  backend/app/database/repository.py
  backend/app/service/ai_serving.py
Labels: feat

#123 [feat #121] Voice Cloning AI 모델 서빙
  backend/app/ai_models/text_generation/token_limit.py
  backend/app/ai_models/voice_cloning/xtts.py
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/database/orm.py
  backend/app/schema/request.py
  backend/app/service/ai_serving.py
Labels: feat

#126 [feat #124] 이전 채팅 가져오기
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/database/repository.py
  backend/app/service/ai_serving.py
Labels: feat

#127 [fix #125] voice cloning tensor 저장 방식 수정
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: fix

#131 [feat #130] 마이페이지 회원탈퇴, 비밀번호 변경 완료
  backend/app/api/user.py
  backend/app/database/orm.py
  backend/app/schema/request.py
Labels: feat

#134 [refactor #133] MySQL sqlalchemy 리팩토링
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/database/connection.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  backend/app/main.py
  backend/app/schema/request.py
  backend/app/service/ai_serving.py
  docker-compose.yml
Labels: refactor

#132 [feat #128] 채팅 보이스피싱 탐지 연결
  backend/app/ai_models/text_generation/chat_generation.py
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
Labels: feat

#137 [feat #136] aws s3 이미지 업로드 기능 추가
  backend/app/api/star.py
  backend/app/database/repository.py
Labels: feat

#139 [feat #138] Voice cloning 반환 데이터 base64 인코딩
  backend/app/api/chat.py
  backend/app/api/star.py
Labels: feat

#141 [fix #140] voice cloning 출력 전달 방식 수정
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/service/ai_serving.py
Labels: fix

#143 [fix #142] p_data 입력오류 수정
  backend/app/api/chat.py
Labels: fix, emergency

#145 [refactor #144] AWS S3 이미지 업로드 클래스화
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/service/s3_service.py
Labels: refactor

#148 [fix #147] voice cloning 오류 수정
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
Labels: fix

#149 [feat #135] 토큰 제한 오류 수정
  backend/app/ai_models/text_generation/token_limit.py
Labels: fix

#153 [feat #152] star 수정
  backend/app/api/star.py
  backend/app/database/orm.py
  backend/app/database/repository.py
  backend/app/schema/request.py
Labels: feat

#157 [feat #156] 음성 복원 S3 업로드 및 URL 반환
  backend/app/api/chat.py
  backend/app/api/star.py
  backend/app/api/user.py
  backend/app/service/ai_serving.py
  backend/app/service/s3_service.py
Labels: feat

#159 [fix #158] ai 코드 리팩토링
  backend/app/ai_models/__init__.py
  backend/app/ai_models/speaker_identification/README.md
  backend/app/ai_models/speaker_identification/__init__.py
  backend/app/ai_models/speaker_identification/clova_speech.py
  backend/app/ai_models/text_generation/README.md
  backend/app/ai_models/text_generation/__init__.py
  backend/app/ai_models/text_generation/crime_prevention.py
  backend/app/ai_models/voice_cloning/README.md
  backend/app/ai_models/voice_cloning/__init__.py
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
Labels: fix

#161 [doc #160] requirements.txt 수정
  backend/requirements.txt
Labels: doc

#167 [doc #164] requirements.txt 업데이트
  backend/app/api/chat.py
  backend/app/service/ai_serving.py
  backend/requirements.txt
Labels: doc
